# Generated by Django 3.2.3 on 2021-07-27 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='author',
        ),
    ]
